"""
Example demonstrating the Shared Sentence Transformer Vectorizer.

This vectorizer connects to a local background model server to share a single
SentenceTransformer model instance across multiple processes. This drastically
reduces VRAM usage and prevents Out-Of-Memory (OOM) errors in multi-process environments.

Key Features Tested:
- Automatic background server spawning
- Multi-process connection to the same server
- Concurrent vectorization without loading multiple models
- Graceful server lifecycle management
"""

import os
import time
import socket
import multiprocessing
from pathlib import Path
from concurrent.futures import ProcessPoolExecutor, as_completed

import safe_store
from safe_store import LogLevel
from ascii_colors import ASCIIColors


def check_port_in_use(port: int, host: str = "127.0.0.1") -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex((host, port)) == 0


def cleanup_db_files(db_file: str):
    db_path = Path(db_file)
    paths_to_delete = [
        db_path,
        Path(f"{db_path}.lock"),
        Path(f"{db_path}-wal"),
        Path(f"{db_path}-shm")
    ]
    for p in paths_to_delete:
        p.unlink(missing_ok=True)


def worker_process(
    process_id: int,
    db_path: str,
    port: int,
    model_name: str
) -> dict:
    """
    Worker process that instantiates SafeStore, adds a document, and queries it.
    All workers connect to the same background model server.
    """
    try:
        store = safe_store.SafeStore(
            db_path=db_path,
            vectorizer_name="sentense_transformer",
            vectorizer_config={
                "model_name": model_name,
                "use_shared_server": True,
                "port": port
            },
            log_level=LogLevel.WARNING
        )

        with store:
            doc_text = f"""
            # Process {process_id} Document
            
            This is a test document generated by process {process_id}.
            It contains unique text about concurrency and shared memory.
            The process ID is {process_id} and it is running successfully.
            """

            store.add_text(
                unique_id=f"doc_process_{process_id}.md",
                text=doc_text,
                metadata={"process_id": process_id, "type": "shared_test"}
            )

            results = store.query("concurrency and shared memory", top_k=1)
            
            if not results:
                return {"process_id": process_id, "status": "error", "message": "No results found"}
            
            top_result = results[0]
            expected_doc = f"doc_process_{process_id}.md"
            actual_doc = Path(top_result["file_path"]).name
            
            return {
                "process_id": process_id,
                "status": "success",
                "found_doc": actual_doc,
                "is_correct_doc": actual_doc == expected_doc,
                "similarity": top_result["similarity_percent"]
            }

    except Exception as e:
        return {"process_id": process_id, "status": "error", "message": str(e)}


def main():
    db_file = "shared_vectorizer_test.db"
    port = 8765
    model_name = "all-MiniLM-L6-v2"
    num_workers = 3

    ASCIIColors.cyan("\n" + "=" * 60)
    ASCIIColors.cyan(" Shared Sentence Transformer Vectorizer Example ")
    ASCIIColors.cyan("=" * 60)

    ASCIIColors.yellow("\n[1] Cleaning up previous test artifacts...")
    cleanup_db_files(db_file)
    if check_port_in_use(port):
        ASCIIColors.red(f"Error: Port {port} is already in use. Please free it before running.")
        return

    ASCIIColors.yellow("\n[2] Spawning concurrent worker processes...")
    ASCIIColors.info(f"Launching {num_workers} parallel SafeStore instances.")
    ASCIIColors.info(f"Expected behavior: Only the first instance spawns the server; others connect to it.")

    start_time = time.time()

    with ProcessPoolExecutor(max_workers=num_workers) as executor:
        futures = [
            executor.submit(
                worker_process,
                i,
                db_file,
                port,
                model_name
            )
            for i in range(num_workers)
        ]

        results = []
        for future in as_completed(futures):
            res = future.result()
            results.append(res)
            if res["status"] == "success":
                ASCIIColors.green(f"  Worker {res['process_id']} completed: Found doc '{res['found_doc']}' (Sim: {res['similarity']:.2f}%)")
            else:
                ASCIIColors.red(f"  Worker {res['process_id']} failed: {res.get('message', 'Unknown error')}")

    elapsed = time.time() - start_time

    ASCIIColors.yellow("\n[3] Verifying results...")
    successful_workers = [r for r in results if r["status"] == "success"]
    correct_workers = [r for r in successful_workers if r["is_correct_doc"]]

    if len(successful_workers) == num_workers and len(correct_workers) == num_workers:
        ASCIIColors.green(f"\nSUCCESS: All {num_workers} workers completed successfully.")
        ASCIIColors.green(f"Each worker correctly retrieved its own document via the shared server.")
    else:
        ASCIIColors.red(f"\nFAILURE: Only {len(correct_workers)}/{num_workers} workers returned correct results.")

    ASCIIColors.info(f"\nTotal execution time: {elapsed:.2f} seconds")

    ASCIIColors.yellow("\n[4] Checking server lifecycle...")
    if check_port_in_use(port):
        ASCIIColors.warning(f"Server is still running on port {port}.")
        ASCIIColors.info("This is expected if the idle timeout has not been reached.")
        ASCIIColors.info("The server will automatically shut down after 1 hour of inactivity.")
    else:
        ASCIIColors.info("Server has already shut down.")

    ASCIIColors.yellow("\n[5] Final cleanup...")
    cleanup_db_files(db_file)
    ASCIIColors.green("Test artifacts cleaned up.")

    ASCIIColors.cyan("\n" + "=" * 60)
    ASCIIColors.cyan(" Example Completed ")
    ASCIIColors.cyan("=" * 60 + "\n")


if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()